apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-delete-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-delete-tasks-api
  template:
    metadata:
      labels:
        app: todo-delete-tasks-api
    spec:
      containers:
      - name: todo-delete-tasks-api
        image: acrtodoappsaurav9454.azurecr.io/deletetask:v1
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sauravsql-dev.database.windows.net,1433;Database=sauravdb-dev123;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
