name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 001db49b-d412-42fd-a9cc-f52510276eba
          tenant-id: 4cdd4678-908a-4b16-946b-2f469301a974
          subscription-id: acd9510d-7e29-433d-8504-d10d34dba654

      - name: Log in to ACR
        run: |
          az acr login --name acrtodoappsaurav9454
      - name: Build Docker Image
        run: |
          docker build -t microtodoui MicroTodoUI
      - name: Tag Docker Image for ACR
        run: |
          docker tag microtodoui acrtodoappsaurav9454.azurecr.io/microtodoui:v1
      - name: Push Docker Image to ACR
        run: |
          docker push acrtodoappsaurav9454.azurecr.io/microtodoui:v1
